name: Test Ansible roles with Molecule
description: Run Molecule to test Ansible roles
author: Open Microscopy Environment

inputs:
  options:
    description: Options you can pass to [`tox`](https://tox.readthedocs.io/en/latest/), for example `--parallel all`.
    required: false
  command:
    description: What command to pass to [molecule](https://molecule.readthedocs.io/en/latest/), for example `lint` or `syntax`.
    required: false
    default: test
  scenario:
    description: The molecule scenario to run.
    required: false
    default: default

runs:
  using: docker
  # It's possible to build the Docker image in the action:
  # image: 'Dockerfile'
  # but this takes around 2m20s compared to 20s to pull a pre-built image
  image: 'docker://manics/docker-github-action-molecule:latest'
  env:
    options: ${{ inputs.options }}
    command: ${{ inputs.command }}
    scenario: ${{ inputs.scenario }}

branding:
  icon: play
  color: green
