name: Molecule action
description: Run Molecule to test Ansible roles
author: Robert de Bock <robert@meinit.nl>

inputs:
  namespace:
    description: The Docker Hub namespace where the image is in.
    required: false
    default: robertdebock
  image:
    description: The image you want to run on.
    required: false
    default: fedora
  tag:
    description: The tag of the container image to use.
    required: false
    default: latest
  options:
    description: Options you can pass to tox, for example `parallel`.
    required: false
    default: ""
 
runs:
  using: docker
  image: 'docker://robertdebock/github-action-molecule'
  env:
    namespace: ${{ inputs.namespace }}
    image: ${{ inputs.image }}
    tag: ${{ inputs.tag }}

branding:
  icon: play  
  color: green

